nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "8008:80"
php:
  build: images/php
  volumes:
    - ./lumen:/var/www/html
  working_dir: /var/www/html/public
  command: php-fpm
  links:
    - db
  ports:
    - "9009:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: TADJJRKSD4564JFSDT234
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: tr5yrrt5y5634r
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
db:
  image: mysql
  ports:
    - "3308:3306"
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
  environment:
    MYSQL_ROOT_PASSWORD: 4rt6yrty7u65yH
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: tr5yrrt5y5634r
    
ui:
  build: vue
  volumes: 
    - ./vue/app:/app
  ports:
    - "8081:8080"